[package]
name = "web_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
reqwest = "0.12.19"
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version="1.45.1", features=["full"] }
url = "2.5.4"

